version: '3.8'

services:
  lower_YT_music_databse:
    image: mysql:8.0
    container_name: lower_YT_music_databse
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
